mavros: update to 0.26.0
mavros-msgs: adjust dependencies

mavros-msgs: adjust dependencies

mavros: adjust dependencies

mavros: drop unused patches

mavros: update to 0.24.0

libmavconn: drop patch included in 0.24.0

mavros: include bash as run-time dependency

This commit resolves:
```
ERROR: mavros-0.24.0-r0 do_package_qa: QA Issue:
/opt/ros/kinetic/lib/mavros/install_geographiclib_datasets.sh
contained in package mavros requires /bin/bash,
but no providers found in RDEPENDS_mavros? [file-rdeps]
```

mavros: update to 0.26.0